language: elixir
elixir:
  - 1.2.5
  - 1.3.2
otp_release:
  - 18.3
  - 19.0
matrix:
  exclude:
    - otp_release: 19.0
      elixir: 1.2.5
addons:
  postgresql: "9.4"
before_script:
  - cp config/test.travis.exs config/test.exs
  - mix deps.get
script:
  - mix test
