language: elixir
elixir:
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.4.0
  - 1.4.1
otp_release:
  - 18.3
  - 19.0
  - 19.1
  - 19.2
addons:
  postgresql: "9.4"
before_script:
  - cp config/test.travis.exs config/test.exs
  - mix deps.get
script:
  - mix test
