# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    # Set up the repository and fetch deps
    - run: mix local.hex --force
    - run: mix local.rebar --force
    - run: cp config/test.ci.exs config/test.exs
    - run: mix deps.get
    # Check source code format
    - run: mix format --check-formatted
    # Create the test database and run the tests
    - run: mix ecto.create
    - run: mix test

jobs:
  "elixir-1.6":
    <<: *shared
    docker:
      - image: circleci/elixir:1.6
      - image: circleci/postgres:9.4
  "elixir-1.7":
    <<: *shared
    docker:
      - image: circleci/elixir:1.7
      - image: circleci/postgres:9.4
  "elixir-1.8":
    <<: *shared
    docker:
      - image: circleci/elixir:1.8
      - image: circleci/postgres:9.4
  "elixir-1.9":
    <<: *shared
    docker:
      - image: circleci/elixir:1.9
      - image: circleci/postgres:9.4
  "elixir-1.10":
    <<: *shared
    docker:
      - image: circleci/elixir:1.10
      - image: circleci/postgres:9.4

workflows:
  version: 2
  build:
    jobs:
      - "elixir-1.6"
      - "elixir-1.7"
      - "elixir-1.8"
      - "elixir-1.9"
      - "elixir-1.10"
